### ISSUE TITLE
Should Code Favor Single Exit or Short Circuit With Multiple Exits?

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/CodingStandards#85]
Which is preferable:
```
if(SomeCondition) 
{
     return 42;
}
return 77*7;
```
or:
```
string data;
if(SomeCondition)
{
   data = 42;
}
else
{
   data = 77*7;
}
return data;
```

Regardless, should there be a guideline or is this just a matter of opinion and context?

**Comment by GrantErickson** [comment]
I personally prefer the short circuit option because it is fewer lines of code and at first glance easier to understand what is happening. Objectively, there are fewer concepts to understand. 

However, let's take a case of an EF expression where we are adding multiple conditions to it based on parameters and then returning a result. In that case, the bottom return variable option is the obvious way to do it. This is definitely not a shall, but I think maybe language like this...

Prefer returning results from a function as soon as they are available instead of having nested structures. Create return variables when they are structurally needed to keep things DRY, provide additional clarity, or simplify logic.

**Comment by Keboo** [comment]
I propose that our coding standards explicitly not take a stance of this. There are reasonable examples for both sides and I would say the better guidance is to reduce nesting within a method.

**Comment by MarkMichaelis** [comment]
Agreed!

**Comment by GrantErickson** [comment]
I agree as well. Seems like readability and not brevity is the order of the day.
